### ISSUE TITLE
Cannot download with install_github

### ISSUE THREAD

**Issue by FrancescoGarassino** [Tomeopaste/AQ_curves#2]
Hi, I'm trying to download your code into R but if I try to use install_github I get errors as:

devtools::install_github(Tomeopaste/AQ_curves)
Error in lapply(repo, github_remote, ref = ref, subdir = subdir, auth_token = auth_token,  : 
  object 'Tomeopaste' not found

**Comment by Tomeopaste** [comment]
Hi Francesco,

This is not setup as a package so there is nothing to install. You can load
the light response function by running:

source("
https://raw.githubusercontent.com/Tomeopaste/AQ_curves/master/AQ_curve_function.R
")

This will execute the script for the function and make it available in your
environment.

Cheers,
Nick

**Comment by FrancescoGarassino** [comment]
Hi Nick,

Sorry it took me forever to get back to this, but thank you for helping me out with my github illiteracy ;)

Cheers,
Francesco
